name: auth-tests

on:
  pull_request:
    paths:
    - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.17.x'
      - run: cd auth && npm install && npm run test:ci
