name: orders-tests

on:
  pull_request:
    paths:
    - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: node-version: '16.17'
      - run: cd orders && npm install && npm run test:ci
